version: 0.0
os: linux
files:
  - source: . 
    destination: /home/deploy/current
permissions:
  - object: /home/deploy/
    owner: deploy
    group: deploy
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: afterdeploy.sh
      runas: deploy
      timeout: 120
      mode: 755
  BeforeInstall:
    - location: beforedeploy.sh
      runas: deploy
      timeout: 120
      mode: 755
